#!/usr/bin/env python3
"""PreToolUse guard: the handful of project-wide mistakes that cost hours (see CLAUDE.md).
Exit 2 + stderr = deny with a message the agent sees. Anything else passes."""
import json, os, re, subprocess, sys

def deny(msg):
    print(msg, file=sys.stderr); sys.exit(2)

try:
    ev = json.load(sys.stdin)
except Exception:
    sys.exit(0)
tool, inp, cwd = ev.get("tool_name", ""), ev.get("tool_input", {}) or {}, ev.get("cwd", "") or ""

if tool == "Bash":
    cmd = inp.get("command", "") or ""
    # 1. lake must run from verification/. Running it inside formalization/ re-clones and compiles Mathlib.
    if re.search(r"\blake\b", cmd):
        segs = re.split(r"&&|;|\|\||\n", cmd)
        in_form = cwd.rstrip("/").endswith("/formalization")
        for s in segs:
            if re.search(r"\bcd\s+\S*formalization/?\s*$", s.strip()):
                in_form = True
            if re.search(r"\bcd\s+\S*verification/?\s*$", s.strip()):
                in_form = False
            if in_form and re.search(r"\blake\b", s):
                deny("guard: run lake from verification/ (formalization/ is a dependency; lake there re-clones Mathlib). "
                     "Use: cd <worktree>/verification && lake build NSFormalization.Foo.Bar")
    # 2. main only changes through a reviewed PR.
    if re.search(r"\bgit\s+push\b[^\n;&|]*\b(HEAD:)?main\b", cmd):
        deny("guard: never push to main directly; open a PR from erenup/integration.")
    # 3. bare git stash is unsafe with shared worktrees.
    if re.search(r"\bgit\s+stash\s*(pop\b|$|;|&&|\|)", cmd):
        deny("guard: no bare `git stash`/`stash pop` (stash stack is shared across worktrees); make a WIP commit instead.")
    sys.exit(0)

if tool in ("Edit", "Write", "MultiEdit"):
    path = inp.get("file_path", "") or ""
    rel = path
    m = re.search(r"(?:^|/)(collaboration/(?:tasks/[^/]+\.md|TASKS\.md))$", path)
    if m:
        deny("guard: %s is generated by `python3 experiments/tasks.py render`; hand edits are overwritten. "
             "Attempts go to research/<ID>/ATTEMPTS*.md." % m.group(1))
    if re.search(r"(?:^|/)paper/.*\.tex$", path):
        deny("guard: paper/ is the owner's manuscript; do not edit it. Record issues under logs/.")
    m = re.search(r"(?:^|/)(verification/(?:Contracts/V1|Tests)/[^/]+\.lean)$", path)
    if m and os.path.exists(path):
        try:
            tracked = subprocess.run(["git", "ls-files", "--error-unmatch", path], cwd=os.path.dirname(path),
                                     capture_output=True).returncode == 0
        except Exception:
            tracked = False
        if tracked:
            deny("guard: %s is a frozen contract/test (tracked). Do not modify; add a V2 under Contracts/V2/ "
                 "or a new file." % m.group(1))
sys.exit(0)
