import NSFormalization.Section3.T12.CutoffGagliardo

namespace NSFormalization.Section3.T12

#print axioms meanZeroPartT_eq_self
#print axioms cFrac_half_pos
#print axioms cFrac_half_lt_top
#print axioms cFrac_half_ne_zero
#print axioms cFrac_half_ne_top
#print axioms ireal_cutoffMul_eq
#print axioms itorus_meanZero_eq
#print axioms enn_sqrt_div_bound
#print axioms gA
#print axioms gB
#print axioms IA
#print axioms IB
#print axioms lintegral_two_add_two
#print axioms measurable_gA_pair
#print axioms measurable_gB_pair
#print axioms ireal_cutoffMul_le_split
#print axioms dotHomogeneousENorm_cutoffMul_le
#print axioms tsupport_cutoff_closedBall
#print axioms cutoff_eq_zero_of_not_mem
#print axioms ofReal_cutoff_sq_le_indicator
#print axioms fractionalRadialKernel_neg
#print axioms periodicKernel_neg
#print axioms latticeVector_add
#print axioms periodicKernel_add_latticeVector
#print axioms coordinateVector_eq_latticeVector
#print axioms periodicKernel_add_coordinateVector
#print axioms measurable_periodicKernel
#print axioms measurable_cubeInnerIntegrand
#print axioms cubeInner
#print axioms measurable_cubeInner
#print axioms isPeriodicSpatial_cubeInner
#print axioms norm_smul_sq
#print axioms gPsi
#print axioms measurable_gPsi
#print axioms iA_inner_sub
#print axioms measurable_innerFrac
#print axioms iA_transform
#print axioms itorus_eq_cubeInner
#print axioms lattice_count_le
#print axioms iA_bound
#print axioms jkernel_lt_top
#print axioms cutoffLip
#print axioms cutoffLip_spec
#print axioms cutoffLip_nonneg
#print axioms cutoff_diff_sq_le_lip
#print axioms cutoff_diff_sq_le_one
#print axioms sq_eLpNorm_two_measure
#print axioms sq_eLpNorm_restrict_eq
#print axioms ballMass_le
#print axioms chiBall
#print axioms measurable_chiBall
#print axioms Ecut
#print axioms measurable_Ecut
#print axioms Jval
#print axioms Jval_lt_top
#print axioms cbConst
#print axioms cbConst_nonneg
#print axioms ofReal_cutoff_diff_sq_le_Ecut
#print axioms ofReal_cutoff_diff_sq_le_split
#print axioms gP1
#print axioms gP2
#print axioms measurable_gP1_pair
#print axioms gB_le_split
#print axioms iB_bound
#print axioms cutoffGagliardoConst
#print axioms cutoffGagliardoConst_pos
#print axioms cutoff_gagliardo_half

end NSFormalization.Section3.T12
