import NSFormalization.Section3.T11.ExtendsBeyond

open NSFormalization.Section3.T11

#print axioms lifespan_ge_of_horizon
#print axioms lifespan_ge_of_extends
#print axioms extendsBeyond_of_input
#print axioms periodicMaximalExistenceInput_of_input
#print axioms exists_maximal_of_input
#print axioms lifespanInfiniteOfLocallyFinite_of_input
#print axioms squaredHTwoIntegralT_ne_top_of_lt
#print axioms constantVelocitySolutionT
#print axioms squaredHTwoIntegralT_constant_ne_top
