import NSFormalization.Section3.T24.MultipleOmegaAssembled
#print axioms NSFormalization.Section3.T24.RegionsOmegaData.placement
#print axioms NSFormalization.Section3.T24.RegionsOmegaData.placement_time
#print axioms NSFormalization.Section3.T24.RegionsOmegaData.placement_chart
#print axioms NSFormalization.Section3.T24.RegionsOmegaData.ε
#print axioms NSFormalization.Section3.T24.RegionsOmegaData.eps_admissible
#print axioms NSFormalization.Section3.T24.RegionsOmegaData.eps_time
#print axioms NSFormalization.Section3.T24.RegionsOmegaData.raw_velocity_smooth
#print axioms NSFormalization.Section3.T24.RegionsOmegaData.raw_pressure_smooth
#print axioms NSFormalization.Section3.T24.RegionsOmegaData.raw_velocity_slab
#print axioms NSFormalization.Section3.T24.RegionsOmegaData.raw_pressure_slab
#print axioms NSFormalization.Section3.T24.RegionsOmegaData.raw_initial
#print axioms NSFormalization.Section3.T24.RegionsOmegaData.raw_support
#print axioms NSFormalization.Section3.T24.RegionsOmegaData.component_force_support
#print axioms NSFormalization.Section3.T24.RegionsOmegaData.component
#print axioms NSFormalization.Section3.T24.RegionsOmegaData.component_pin
#print axioms NSFormalization.Section3.T24.RegionsOmegaData.component_support
#print axioms NSFormalization.Section3.T24.smoothOnClosedSlab_finset_sum
#print axioms NSFormalization.Section3.T24.forceClassOmega_finset_sum
#print axioms NSFormalization.Section3.T24.RegionsOmegaData.assembledVelocity
#print axioms NSFormalization.Section3.T24.RegionsOmegaData.assembledPressure
#print axioms NSFormalization.Section3.T24.RegionsOmegaData.assembledForce
#print axioms NSFormalization.Section3.T24.RegionsOmegaData.assembled_velocity_formula
#print axioms NSFormalization.Section3.T24.RegionsOmegaData.assembled_pressure_formula
#print axioms NSFormalization.Section3.T24.RegionsOmegaData.assembled_force_formula
#print axioms NSFormalization.Section3.T24.RegionsOmegaData.assembled_velocity_smooth
#print axioms NSFormalization.Section3.T24.RegionsOmegaData.assembled_pressure_smooth
#print axioms NSFormalization.Section3.T24.RegionsOmegaData.rest
#print axioms NSFormalization.Section3.T24.RegionsOmegaData.component_force_mem
#print axioms NSFormalization.Section3.T24.RegionsOmegaData.force_mem
#print axioms NSFormalization.Section3.T24.RegionsOmegaData.component_slice
#print axioms NSFormalization.Section3.T24.RegionsOmegaData.component_pressure_slice
#print axioms NSFormalization.Section3.T24.RegionsOmegaData.component_nonoverlap
#print axioms NSFormalization.Section3.T24.RegionsOmegaData.crossTransport_eq_zero
#print axioms NSFormalization.Section3.T24.RegionsOmegaData.assembled_spatialDerivative
#print axioms NSFormalization.Section3.T24.RegionsOmegaData.assembled_divergence
#print axioms NSFormalization.Section3.T24.RegionsOmegaData.assembled_pressure_gauge
#print axioms NSFormalization.Section3.T24.RegionsOmegaData.component_temporal
#print axioms NSFormalization.Section3.T24.RegionsOmegaData.assembled_temporalDerivative
#print axioms NSFormalization.Section3.T24.RegionsOmegaData.assembled_spatialLaplacian
#print axioms NSFormalization.Section3.T24.RegionsOmegaData.assembled_pressureGradient
#print axioms NSFormalization.Section3.T24.RegionsOmegaData.assembled_advection
#print axioms NSFormalization.Section3.T24.RegionsOmegaData.assembled_momentum
#print axioms NSFormalization.Section3.T24.RegionsOmegaData.no_slip
#print axioms NSFormalization.Section3.T24.RegionsOmegaData.solution
#print axioms NSFormalization.Section3.T24.RegionsOmegaData.solution_pin
