import NSFormalization.Section4.R42.Lifespan

open NSFormalization.Section4.R42

#print axioms limsup_eq_top_of_le_add_const
#print axioms eLpNormTop_le_ofReal
#print axioms eLpNormTop_le_add
#print axioms limsup_eLpNormTop_add_eq_top
#print axioms hasCompactSupport_of_tsupport_subset_ball
#print axioms exists_isSobolevDatum_of_contDiff_hasCompactSupport
#print axioms memForceR_insertedForce
#print axioms lt_maximalLifespanR_of_regularThrough
