import Tests.PeriodicInsertion

#print axioms NSFormalization.Section3.T18.assemble
#print axioms NSFormalization.Section3.T18.periodicInsertionStatement
#print axioms NSFormalization.Section3.T18.periodicInsertionStatement_holds
#print axioms NSFormalization.Section3.T18.nonvacuity_of_witnesses
#print axioms BlowupDensity.Bindings.PeriodicInsertion.placementOfSpec
#print axioms BlowupDensity.Bindings.PeriodicInsertion.localizationOfSpec
#print axioms BlowupDensity.Bindings.PeriodicInsertion.potentialOfSpec
#print axioms BlowupDensity.Bindings.PeriodicInsertion.scalingOfSpec
#print axioms BlowupDensity.Bindings.PeriodicInsertion.correctionOfSpec
#print axioms BlowupDensity.Bindings.PeriodicInsertion.ofSpecInputs
#print axioms BlowupDensity.Bindings.PeriodicInsertion.packet_energyBound_nonneg
#print axioms BlowupDensity.Bindings.PeriodicInsertion.packet_dissipationBound_nonneg
#print axioms BlowupDensity.Bindings.PeriodicInsertion.toSpecAPI
#print axioms BlowupDensity.Bindings.PeriodicInsertion.ofSpecAPI
#print axioms BlowupDensity.Bindings.PeriodicInsertion.api_to_of
#print axioms BlowupDensity.Bindings.PeriodicInsertion.api_of_to
#print axioms BlowupDensity.Bindings.PeriodicInsertion.periodicInsertion
#print axioms BlowupDensity.Bindings.PeriodicInsertion.periodicInsertionStatement_holds
#print axioms BlowupDensity.Bindings.PeriodicInsertion.scaledStartTime_eq
#print axioms BlowupDensity.Bindings.PeriodicInsertion.scaledSourcePoint_eq
#print axioms BlowupDensity.Bindings.PeriodicInsertion.IsPeriodicLebesgueSlicePath_eq
#print axioms BlowupDensity.Bindings.PeriodicInsertion.mixedLebesgueENormT_eq
#print axioms BlowupDensity.Bindings.PeriodicInsertion.MemMixedLebesgueR_eq
#print axioms BlowupDensity.Bindings.PeriodicInsertion.MemMixedLebesgueT_eq
#print axioms BlowupDensity.Bindings.PeriodicInsertion.MemForceSobolevT_eq
#print axioms BlowupDensity.Bindings.PeriodicInsertion.EnergySlicesMemLpT_eq
#print axioms BlowupDensity.Bindings.PeriodicInsertion.alphaT_eq
#print axioms BlowupDensity.Bindings.PeriodicInsertion.scaledVelocity_eq
#print axioms BlowupDensity.Bindings.PeriodicInsertion.scaledPressure_eq
#print axioms BlowupDensity.Bindings.PeriodicInsertion.scaledForce_eq
#print axioms BlowupDensity.Bindings.PeriodicInsertion.periodizedScaledVelocity_eq
#print axioms BlowupDensity.Bindings.PeriodicInsertion.periodizedScaledPressure_eq
#print axioms BlowupDensity.Bindings.PeriodicInsertion.periodizedScaledForce_eq
#print axioms BlowupDensity.Bindings.PeriodicInsertion.normalizedScaledPressure_eq
#print axioms BlowupDensity.Bindings.PeriodicInsertion.torusSpaceTimeLift_eq
#print axioms BlowupDensity.Bindings.PeriodicInsertion.torusSpatialSupport_eq
#print axioms BlowupDensity.Bindings.PeriodicInsertion.torusTemporalSupport_eq
#print axioms BlowupDensity.Bindings.PeriodicInsertion.fixedProfileCylinder_eq
#print axioms BlowupDensity.Bindings.PeriodicInsertion.correctionForce_eq
#print axioms BlowupDensity.Bindings.PeriodicInsertion.correctionChartPoint_eq
#print axioms BlowupDensity.Bindings.PeriodicInsertion.rescaledReference_eq
#print axioms BlowupDensity.Bindings.PeriodicInsertion.rescaledPotential_eq
#print axioms BlowupDensity.Bindings.PeriodicInsertion.rescaledCorrectionProfile_eq
#print axioms BlowupDensity.Bindings.PeriodicInsertion.rescaledForceProfile_eq
#print axioms BlowupDensity.Bindings.PeriodicInsertion.placementToSpec
#print axioms BlowupDensity.Bindings.PeriodicInsertion.placement_to_of
#print axioms BlowupDensity.Bindings.PeriodicInsertion.placement_of_to
#print axioms BlowupDensity.Bindings.PeriodicInsertion.scalingToSpec
#print axioms BlowupDensity.Bindings.PeriodicInsertion.scaling_to_of
#print axioms BlowupDensity.Bindings.PeriodicInsertion.scaling_of_to
#print axioms BlowupDensity.Bindings.PeriodicInsertion.correctionToSpec
#print axioms BlowupDensity.Bindings.PeriodicInsertion.correction_to_of
#print axioms BlowupDensity.Bindings.PeriodicInsertion.correction_of_to
#print axioms BlowupDensity.Bindings.PeriodicInsertion.correctionPlacement_eq
#print axioms BlowupDensity.Bindings.PeriodicInsertion.nonvacuity_of_witnesses
#print axioms BlowupDensity.Bindings.PeriodicInsertion.periodicInsertionStatement_iff
#print axioms BlowupDensity.Tests.checkedPeriodicInsertion

#print axioms NSFormalization.Section3.T18.PeriodicInsertionAPI
#print axioms NSFormalization.Section3.T18.RawPremises
#print axioms BlowupDensity.T15.Draft.scaledStartTime
#print axioms BlowupDensity.T15.Draft.scaledSourcePoint
#print axioms BlowupDensity.T15.Draft.scaledVelocity
#print axioms BlowupDensity.T15.Draft.scaledPressure
#print axioms BlowupDensity.T15.Draft.scaledForce
#print axioms BlowupDensity.T15.Draft.periodizedScaledVelocity
#print axioms BlowupDensity.T15.Draft.periodizedScaledPressure
#print axioms BlowupDensity.T15.Draft.periodizedScaledForce
#print axioms BlowupDensity.T15.Draft.normalizedScaledPressure
#print axioms BlowupDensity.T15.Draft.IsPeriodicLebesgueSlicePath
#print axioms BlowupDensity.T15.Draft.mixedLebesgueENormT
#print axioms BlowupDensity.T15.Draft.MemMixedLebesgueR
#print axioms BlowupDensity.T15.Draft.MemMixedLebesgueT
#print axioms BlowupDensity.T15.Draft.MemForceSobolevT
#print axioms BlowupDensity.T15.Draft.EnergySlicesMemLpT
#print axioms BlowupDensity.T15.Draft.alphaT
#print axioms BlowupDensity.T15.Draft.ScalingAPI
#print axioms BlowupDensity.T18.Spec.PeriodicInsertionAPI
#print axioms BlowupDensity.T18.Spec.periodicInsertionStatement
