import Bindings.Scaling3
import Tests.Scaling3

#print axioms NSFormalization.Section3.T15.placementCenter
#print axioms NSFormalization.Section3.T15.placementCarrier
#print axioms NSFormalization.Section3.T15.placementCarrier_compact
#print axioms NSFormalization.Section3.T15.placementCarrier_bound
#print axioms NSFormalization.Section3.T15.placementRadius
#print axioms NSFormalization.Section3.T15.placementRadius_pos
#print axioms NSFormalization.Section3.T15.placement_norm_le_radius
#print axioms NSFormalization.Section3.T15.placementThreshold
#print axioms NSFormalization.Section3.T15.placementThreshold_pos
#print axioms NSFormalization.Section3.T15.placement_chart_in_cube
#print axioms NSFormalization.Section3.T15.placementData
#print axioms NSFormalization.Section3.T15.placementData_time
#print axioms NSFormalization.Section3.T15.scalingAPI
#print axioms NSFormalization.Section3.T15.scalingStatement_holds
#print axioms BlowupDensity.Bindings.Scaling3.placementOfSpec
#print axioms BlowupDensity.Bindings.Scaling3.localizationOfSpec
#print axioms BlowupDensity.Bindings.Scaling3.scalingOfSpec
#print axioms BlowupDensity.Bindings.Scaling3.placementToSpec
#print axioms BlowupDensity.Bindings.Scaling3.placement_to_of
#print axioms BlowupDensity.Bindings.Scaling3.placement_of_to
#print axioms BlowupDensity.Bindings.Scaling3.scalingToSpec
#print axioms BlowupDensity.Bindings.Scaling3.scaling_to_of
#print axioms BlowupDensity.Bindings.Scaling3.scaling_of_to
#print axioms BlowupDensity.Bindings.Scaling3.scaledStartTime_eq
#print axioms BlowupDensity.Bindings.Scaling3.scaledSourcePoint_eq
#print axioms BlowupDensity.Bindings.Scaling3.scaledVelocity_eq
#print axioms BlowupDensity.Bindings.Scaling3.scaledPressure_eq
#print axioms BlowupDensity.Bindings.Scaling3.scaledForce_eq
#print axioms BlowupDensity.Bindings.Scaling3.periodizedScaledVelocity_eq
#print axioms BlowupDensity.Bindings.Scaling3.periodizedScaledPressure_eq
#print axioms BlowupDensity.Bindings.Scaling3.periodizedScaledForce_eq
#print axioms BlowupDensity.Bindings.Scaling3.normalizedScaledPressure_eq
#print axioms BlowupDensity.Bindings.Scaling3.IsPeriodicLebesgueSlicePath_eq
#print axioms BlowupDensity.Bindings.Scaling3.mixedLebesgueENormT_eq
#print axioms BlowupDensity.Bindings.Scaling3.MemMixedLebesgueR_eq
#print axioms BlowupDensity.Bindings.Scaling3.MemMixedLebesgueT_eq
#print axioms BlowupDensity.Bindings.Scaling3.MemForceSobolevT_eq
#print axioms BlowupDensity.Bindings.Scaling3.EnergySlicesMemLpT_eq
#print axioms BlowupDensity.Bindings.Scaling3.alphaT_eq
#print axioms BlowupDensity.Bindings.Scaling3.scalingStatement_iff
#print axioms BlowupDensity.Bindings.Scaling3.placementData
#print axioms BlowupDensity.Bindings.Scaling3.placementData_time
#print axioms BlowupDensity.Bindings.Scaling3.scalingAPI
#print axioms BlowupDensity.Bindings.Scaling3.scalingStatement_holds
#print axioms BlowupDensity.Bindings.Scaling3.scalingPacket
#print axioms BlowupDensity.Tests.checkedScaling3
#print axioms BlowupDensity.Tests.checkedScaling3Packet
#print axioms BlowupDensity.Tests.scaling3_source_nonzero
#print axioms BlowupDensity.Tests.scaling3_periodized_nonzero
#print axioms BlowupDensity.Contracts.V1.Scaling3.scaledStartTime
#print axioms BlowupDensity.Contracts.V1.Scaling3.scaledSourcePoint
#print axioms BlowupDensity.Contracts.V1.Scaling3.scaledVelocity
#print axioms BlowupDensity.Contracts.V1.Scaling3.scaledPressure
#print axioms BlowupDensity.Contracts.V1.Scaling3.scaledForce
#print axioms BlowupDensity.Contracts.V1.Scaling3.periodizedScaledVelocity
#print axioms BlowupDensity.Contracts.V1.Scaling3.periodizedScaledPressure
#print axioms BlowupDensity.Contracts.V1.Scaling3.periodizedScaledForce
#print axioms BlowupDensity.Contracts.V1.Scaling3.normalizedScaledPressure
#print axioms BlowupDensity.Contracts.V1.Scaling3.IsPeriodicLebesgueSlicePath
#print axioms BlowupDensity.Contracts.V1.Scaling3.mixedLebesgueENormT
#print axioms BlowupDensity.Contracts.V1.Scaling3.MemMixedLebesgueR
#print axioms BlowupDensity.Contracts.V1.Scaling3.MemMixedLebesgueT
#print axioms BlowupDensity.Contracts.V1.Scaling3.MemForceSobolevT
#print axioms BlowupDensity.Contracts.V1.Scaling3.EnergySlicesMemLpT
#print axioms BlowupDensity.Contracts.V1.Scaling3.alphaT
#print axioms BlowupDensity.Contracts.V1.Scaling3.PlacementData
#print axioms BlowupDensity.Contracts.V1.Scaling3.ScalingAPI
#print axioms BlowupDensity.Contracts.V1.Scaling3.scalingStatement
