import NSFormalization.Section3.T15.Solution

#print axioms NSFormalization.Section3.T15.normalizePressureT_eq_normalizedPressure
#print axioms NSFormalization.Section3.T15.periodizedPressure_contDiffOn
#print axioms NSFormalization.Section3.T15.normalizedScaledPressure_contDiffOn
#print axioms NSFormalization.Section3.T15.isPeriodicOn_normalizePressureT
#print axioms NSFormalization.Section3.T15.periodizedVelocity_periodic
#print axioms NSFormalization.Section3.T15.normalizedScaledPressure_periodic
#print axioms NSFormalization.Section3.T15.periodizedSolution
#print axioms NSFormalization.Section3.T15.solution
