import NSFormalization.Section3.T23.DomainComparison

#print axioms NSFormalization.Section3.T23.domainEnergyEssSup_eq
#print axioms NSFormalization.Section3.T23.domainEnergyGradient_eq
#print axioms NSFormalization.Section3.T23.domainEnergyENorm_eq
#print axioms NSFormalization.Section3.T23.domainForceSobolevENorm_eq
#print axioms NSFormalization.Section3.T23.zeroExtForceSobolevENorm_eq
#print axioms NSFormalization.Section3.T23.tsupport_zeroExtension_subset_of_pointwise_support
#print axioms NSFormalization.Section3.T23.contDiffOn_slice_of_memForceOmega
#print axioms NSFormalization.Section3.T23.domainForceDifference_orderZero
#print axioms NSFormalization.Section3.T23.domain_zeroExt_comparison
