import NSFormalization.Section3.T23.Solution

#print axioms NSFormalization.Section3.T23.domain_volume_pos
#print axioms NSFormalization.Section3.T23.SmoothOnClosedSlab.integrableOn_slice
#print axioms NSFormalization.Section3.T23.domainNormalizePressure_integral
#print axioms NSFormalization.Section3.T23.pressureGradient_domainNormalizePressure
#print axioms NSFormalization.Section3.T23.residual_domainNormalizePressure
#print axioms NSFormalization.Section3.T23.domainIntegral_contDiffOn_nat
#print axioms NSFormalization.Section3.T23.SmoothOnClosedSlab.integral_smooth
#print axioms NSFormalization.Section3.T23.SmoothOnClosedSlab.domainNormalizePressure
#print axioms NSFormalization.Section3.T23.SmoothOnClosedSlab.add
#print axioms NSFormalization.Section3.T23.SmoothOnClosedSlab.mono_time
#print axioms NSFormalization.Section3.T23.smoothOnClosedSlab_of_contDiff
#print axioms NSFormalization.Section3.T23.MemForceOmega.add
#print axioms NSFormalization.Section3.T23.memForceOmega_of_compactPositiveTimeSupport
#print axioms NSFormalization.Section3.T23.domain_residual_add
#print axioms NSFormalization.Section3.T23.InsertedTriple.threshold
#print axioms NSFormalization.Section3.T23.InsertedTriple.velocity
#print axioms NSFormalization.Section3.T23.InsertedTriple.pressure
#print axioms NSFormalization.Section3.T23.InsertedTriple.force
#print axioms NSFormalization.Section3.T23.InsertedTriple.velocity_formula
#print axioms NSFormalization.Section3.T23.InsertedTriple.pressure_formula
#print axioms NSFormalization.Section3.T23.InsertedTriple.force_formula
#print axioms NSFormalization.Section3.T23.InsertedTriple.eps_pos
#print axioms NSFormalization.Section3.T23.InsertedTriple.eps_le_scaling
#print axioms NSFormalization.Section3.T23.InsertedTriple.eps_le_cutoff
#print axioms NSFormalization.Section3.T23.InsertedTriple.eps_le_supplier
#print axioms NSFormalization.Section3.T23.InsertedTriple.eps_le_geometry
#print axioms NSFormalization.Section3.T23.InsertedTriple.packet_velocity_smooth
#print axioms NSFormalization.Section3.T23.InsertedTriple.packet_pressure_smooth
#print axioms NSFormalization.Section3.T23.InsertedTriple.history
#print axioms NSFormalization.Section3.T23.InsertedTriple.initial
#print axioms NSFormalization.Section3.T23.InsertedTriple.velocity_smooth
#print axioms NSFormalization.Section3.T23.InsertedTriple.pressure_smooth
#print axioms NSFormalization.Section3.T23.InsertedTriple.correction_force_mem
#print axioms NSFormalization.Section3.T23.InsertedTriple.packet_force_mem
#print axioms NSFormalization.Section3.T23.InsertedTriple.force_mem
#print axioms NSFormalization.Section3.T23.InsertedTriple.forceDifference_mem
#print axioms NSFormalization.Section3.T23.InsertedTriple.incompressible
#print axioms NSFormalization.Section3.T23.InsertedTriple.corrected_background_momentum
#print axioms NSFormalization.Section3.T23.InsertedTriple.momentum
#print axioms NSFormalization.Section3.T23.InsertedTriple.pressure_gauge
#print axioms NSFormalization.Section3.T23.InsertedTriple.classicalSolution
#print axioms NSFormalization.Section3.T23.InsertedTriple.solution
