import NSFormalization.Section3.T10.ForcePaths

open NSFormalization.Section3.T10

#check memForceT_iff_isTestForce
#print axioms memForceT_iff_isTestForce
#check memLp_torusLift_vector
#print axioms memLp_torusLift_vector
#check smooth_periodic_datum
#print axioms smooth_periodic_datum
#check periodicSobolevENorm_eq
#print axioms periodicSobolevENorm_eq
#check norm_scalar_datum_nat
#print axioms norm_scalar_datum_nat
#check datum_sub
#print axioms datum_sub
#check continuous_datum_path
#print axioms continuous_datum_path
#check force_coefficient_path
#print axioms force_coefficient_path
#check forceSobolevENormT_ne_top
#print axioms forceSobolevENormT_ne_top
#check periodicFourierCoeff_component_derivative
#print axioms periodicFourierCoeff_component_derivative
#check periodicFourierCoeff_component_decay
#print axioms periodicFourierCoeff_component_decay
#check periodicFourierCoeff_component_laplacian
#print axioms periodicFourierCoeff_component_laplacian
#check periodicFourierCoeff_vector_gradient_sq
#print axioms periodicFourierCoeff_vector_gradient_sq
#check gradientTensor_component
#print axioms gradientTensor_component
#check memLp_gradientTensor
#print axioms memLp_gradientTensor
#check gradientTensor_parseval
#print axioms gradientTensor_parseval
#check angularFrequencySq_nonneg
#print axioms angularFrequencySq_nonneg
#check homogeneousDatumWeight_one
#print axioms homogeneousDatumWeight_one
#check summable_angular_component
#print axioms summable_angular_component
#check norm_sqrt_angular_smul_sq
#print axioms norm_sqrt_angular_smul_sq
#check smooth_homogeneous_datum_one
#print axioms smooth_homogeneous_datum_one
#check homogeneousENorm_one_eq
#print axioms homogeneousENorm_one_eq
#check angular_meanZeroPart
#print axioms angular_meanZeroPart
#check gradient_eq_homogeneousENorm
#print axioms gradient_eq_homogeneousENorm
#check sobolevENorm_zero_eq
#print axioms sobolevENorm_zero_eq
#check energyENormT_eq
#print axioms energyENormT_eq
#check memForceT_time_smul
#print axioms memForceT_time_smul
#check periodicFourierCoeff_gradientTensor
#print axioms periodicFourierCoeff_gradientTensor
#check periodicFourierCoeff_vector_laplacian
#print axioms periodicFourierCoeff_vector_laplacian
