import NSFormalization.Section3.T11.EnstrophyInequality
import TestSupport.Axioms

#print axioms NSFormalization.Section3.T11.inhomogeneousEnergyIdentityT
run_cmd BlowupDensity.TestSupport.checkAxioms ``NSFormalization.Section3.T11.inhomogeneousEnergyIdentityT
#print axioms NSFormalization.Section3.T11.lintegral_convection_holder_632T
run_cmd BlowupDensity.TestSupport.checkAxioms ``NSFormalization.Section3.T11.lintegral_convection_holder_632T
#print axioms NSFormalization.Section3.T11.eLpNorm_three_interpolationT
run_cmd BlowupDensity.TestSupport.checkAxioms ``NSFormalization.Section3.T11.eLpNorm_three_interpolationT
#print axioms NSFormalization.Section3.T11.young_quarticT
run_cmd BlowupDensity.TestSupport.checkAxioms ``NSFormalization.Section3.T11.young_quarticT
#print axioms NSFormalization.Section3.T11.young_three_quartersT
run_cmd BlowupDensity.TestSupport.checkAxioms ``NSFormalization.Section3.T11.young_three_quartersT
#print axioms NSFormalization.Section3.T11.young_two_factorsT
run_cmd BlowupDensity.TestSupport.checkAxioms ``NSFormalization.Section3.T11.young_two_factorsT
#print axioms NSFormalization.Section3.T11.weighted_cubic_assemblyT
run_cmd BlowupDensity.TestSupport.checkAxioms ``NSFormalization.Section3.T11.weighted_cubic_assemblyT
#print axioms NSFormalization.Section3.T11.gradient_six_le_laplacian_twoT
run_cmd BlowupDensity.TestSupport.checkAxioms ``NSFormalization.Section3.T11.gradient_six_le_laplacian_twoT
#print axioms NSFormalization.Section3.T11.convection_interpolationT
run_cmd BlowupDensity.TestSupport.checkAxioms ``NSFormalization.Section3.T11.convection_interpolationT
#print axioms NSFormalization.Section3.T11.velocity_six_le_localized_gradientT
run_cmd BlowupDensity.TestSupport.checkAxioms ``NSFormalization.Section3.T11.velocity_six_le_localized_gradientT
