import NSFormalization.Section3.T11.EnstrophyInequality
#print axioms NSFormalization.Section3.T11.inhomogeneousEnergyIdentityT
#print axioms NSFormalization.Section3.T11.lintegral_convection_holder_632T
#print axioms NSFormalization.Section3.T11.eLpNorm_three_interpolationT
